[images]
  remote_images = ["https://api.weatherapi.com/.*", "https://same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  CI = "true"

[dev]
  command = "bun run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
